### ISSUE TITLE
Há dois arquivos chamado Produto.kt que possivelmente podem ser mesclados

### ISSUE THREAD

**Issue by IsadoraPicoli** [gabrielfbarbosa/ProjetoCompassMart#9]
Ambos os arquivos com o nome **Produto.kt** são classes que possuem o mesmo nome, porém atributos diferentes, que podem ser mesclados.
Atualmente os arquivos estão na **branch feature/sprint2**, nos seguintes diretórios:

- [tela_produtos](https://github.com/gabrielfbarbosa/ProjetoCompassMart/tree/feature/sprint2/app/src/main/java/br/com/compass/compassmart/ui/fragment/tela_produtos)
- [tela_carrinhocompras/model](https://github.com/gabrielfbarbosa/ProjetoCompassMart/tree/feature/sprint2/app/src/main/java/br/com/compass/compassmart/ui/fragment/tela_carrinhocompras/model)

@gabrielfbarbosa e @yanokumoto acredito que vocês possam conversar entre si e verificar se é possível ou não fazer essa junção, já os dois mexeram com esses arquivos.
Só um adendo, por ser um arquivo que vai ser utilizado em várias telas, acredito que ficaria bom se deixasse o arquivo final no diretório:
- app/src/main/java/br/com/compass/compassmart/model/Produto.kt

**Comment by gabrielfbarbosa** [comment]
Opa, é uma boa mesmo. Por mim tranquilo fazer isso.

**Comment by yanokumoto** [comment]
prontinho, issue corrigida no "Correções Code Review #2" da feature/produtos -> develop
